### ISSUE TITLE
Employee's can access a log of action taken on a User's account

### ISSUE THREAD

**Issue by AlexRutledge1** [ucf-tower-app/xplat#159]
In order for employees to be able to moderate content effectively it would be helpful if they can see if other employee's have already taken action on the account (action meaning demoting/promoting the user's status level)

**Comment by Henry-Graves** [comment]
Employees will be able to access a log of moderation actions per account where previous action has been taken. This is gonna be stored in it's own db collection and we can display it on frontend through a popup showing previous mod action details.

This is now a bullet point on my epic I'm working on (#105) so I'm closing this issue, thx for bringing it up!
