### ISSUE TITLE
Add more route grade info

### ISSUE THREAD

**Issue by Henry-Graves** [ucf-tower-app/xplat#169]
- [x]  Ropes have a/b/c/d modifiers (-3/-1/+1/+3 for scoreboard value)
- [x] Traverses have Beginner/Intermediate/Advanced (V0-V1/V2-V3/V4+ for scoreboard value)

**Comment by JakeSteinebronn** [comment]
I was kinda wondering if we should still keep +/-, and have + be +2 and - be -2. what do you think @Henry-Graves ?

**Comment by Henry-Graves** [comment]
I prefer that, I think a/b/c/d is too complicated. What do the Tower routes usually use?

**Comment by JakeSteinebronn** [comment]
They currently use +/-, but we've been asked to use a/b/c/d. I'm just saying we should support both, since I doubt every future setter will use the same scheme, and it's not really that much more work for us

**Comment by Henry-Graves** [comment]
oh I see, yeah we should support both and have +/- be +2/-2.
