### ISSUE TITLE
Associate posts with routes

### ISSUE THREAD

**Issue by Henry-Graves** [ucf-tower-app/xplat#170]
**Note:** 

I think this is a design decision we've talked about before. The intention is to be able to view all the posts tied to a route somewhere in the detailed view of the route. Did we decide not to go with this? Worth implementing?

----

- [ ] A post can be associated with a route (as an optional field)
- [ ] get all posts for this route

**Comment by JakeSteinebronn** [comment]
post -> forum -> route is an existing link
route -> forum -> get all posts is a thing

**Comment by Henry-Graves** [comment]
I forgor about the forum connection, thank you
