### ISSUE TITLE
Shadow-swap a user's profile picture, displayname, and bio if reported

### ISSUE THREAD

**Issue by JakeSteinebronn** [ucf-tower-app/xplat#196]
Cuz like if it's profane, it shouldn't be showing up in userTags and such. Equivalent to a shadow-delete of a post or comment

**Comment by JakeSteinebronn** [comment]
I guess it's like in the initWithDocumentData we check if they're bad and if so, swap in some nondescript / default fields. Not shame yet because we dont know if theyre guilty

**Comment by Henry-Graves** [comment]
yeah definitely, we should do it after reaching 3 or 5 reports though so people don't get trolled.
we're getting into magic number territory with report thresholds but I think it's fine rn

**Comment by JakeSteinebronn** [comment]
it's the same magic number as all the other ones, right? we can even use that `checkShouldBeHidden` function

**Comment by Henry-Graves** [comment]
It can be the same magic number, but I think it'd serve us better to have the checkShouldBeHidden threshold lower than the max reports possible on content to give it a little bit of buffer. This would help in the case where users spam back and forth across the threshold and we're rerendering to show/hide content
