### ISSUE TITLE
Deleted user still in blocked list

### ISSUE THREAD

**Issue by abrugal** [ucf-tower-app/xplat#261]
Any blocked lists that a deleted user was in doesn't get updated after deleting the user. In this example the empty space was a blocked user who was then deleted.

![Screenshot_20230418_144332_Expo Go](https://user-images.githubusercontent.com/5271307/232873830-cb4352f9-ac67-47ec-8cf5-939af437a4af.jpg)

**Comment by abrugal** [comment]
Need to go through the blockedByList and update those user's blockList

**Comment by Henry-Graves** [comment]
Good catch, I'm taking this issue
