### ISSUE TITLE
Support Forum and Route derivation from Post

### ISSUE THREAD

**Issue by TylerMathis** [ucf-tower-app/xplat#33]
Most display locations for a `Post` will include their associated `Forum` and `Route` via context; however, more general applications such as a chronological feed do not have this luxury. To solve this, we would like to be able to recover the `Forum` and `Route` from just a `Post` object.

Not all `Post`s will be associated with a `Route`, and some might be free-floating without a `Forum`, so there should also be a fairly idiomatic (maybe monadic) way to retrieve the `Forum` or `Route`, gracefully failing if they do not exist. Supporting a `hasForum`, and `hasRoute` member variable might also be useful.

**Comment by JakeSteinebronn** [comment]
Actually currently a `Post` guarantees a `Forum`, but this shouldn't be the case in the future.

well it's already in the code. This issue sounds more like requesting myelination, but you can already get a `Post`'s `Route` by saying `this.getForum().getRoute()?`

**Comment by TylerMathis** [comment]
As mentioned, this is already supported.
