### ISSUE TITLE
Timestamp not Working Properly

### ISSUE THREAD

**Issue by AlexRutledge1** [ucf-tower-app/xplat#56]
I could be interpreting xplat/api wrong, but it seems that we are storing timestamps in a certain Firebase format and then assuming the timestamp will be accessed as a javascript Date object. Treating it as a Date object throws an error

**Comment by JakeSteinebronn** [comment]
![image](https://user-images.githubusercontent.com/16229422/212764125-64dbe55f-8837-45fc-9063-2a0a752b2fdc.png)
I think it's working? It seems to parse correctly and it prints and stuff. Could you describe where you got this error?

**Comment by AlexRutledge1** [comment]
I could be implementing it incorrectly, but the getTimestamp function returns a Date object but what is actually returns is what you show in the above screenshot; this object does not parse into Date. Below is an example of how I am trying to use it.

![Image](https://user-images.githubusercontent.com/31017536/213022666-a781ae7d-738d-4d14-98f1-00ac759f9e43.png)


![Image](https://user-images.githubusercontent.com/31017536/213022917-9590e9e6-d512-440e-8a3c-310c52336dac.png)

**Comment by AlexRutledge1** [comment]
I worked on a time-stamp implementation over winter break and was able to call getTimestamp and it would act as a Date object without issue. This isn't the case anymore.

**Comment by JakeSteinebronn** [comment]
I thought it already WAS a Date object though... but I'll poke around

**Comment by JakeSteinebronn** [comment]
Fixed! Sorry this caused issues for you <3
