### ISSUE TITLE
Routes will have a userRating [1,5] showing how much users like the route

### ISSUE THREAD

**Issue by Henry-Graves** [ucf-tower-app/xplat#94]
**This is TBD because we're not sure if April & Tower staff will want this as a feature.**

We could store number of ratings as well as an updated average

### Tasks for this requirement:
- [ ]

**Comment by JakeSteinebronn** [comment]
Closed as not planned as per @TylerMathis and @DanielW48 and myself discussing that the tower is unlikely to choose this idea over just likes. Will reopen if otherwise.
